config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  resources :badges, only: %i[ index index_user ]
  get :user_badges, to: 'badges#index_user'

  resources :feedbacks, only: %i[ new create ]

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[ show update ] do
    get :result, on: :member
    post 'gist', to: "gists#create", on: :member
  end

  namespace :admin do
    resources :badges
    resources :feedbacks, only: %i[ index ]

    get 'gists', to: "gists#index" 
    
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  CONDITIONS = %w[ all_tests_in_category all_tests_with_level first_test test_on_the_first_try ].freeze

  has_many :badge_users, dependent: :destroy
  has_many :users, through: :badge_users

  validates :condition, inclusion: { in: CONDITIONS, message: "%{value} is not a valid condition." }
  validates :name, :condition, :image_url, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[ show edit update destroy ]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge), notice: t('.update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path, notice: t('.delete')
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :image_url, :condition, :condition_parameter)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def index_user
    @badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_image_helper(badge)
    badge.image_url.capitalize == 'None' ? badge.image_url : (image_tag badge.image_url, class: 'img-thumbnail w-25')
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class='align-middle'><%= badge_image_helper(badge) %></td>
  <td class='align-middle'><%= link_to badge.name, admin_badge_path(badge) %></td>

  <td class='align-middle'><%= link_to t('.edit'), edit_admin_badge_path(badge) %></td>
  <td class='align-middle'><%= link_to t('.destroy'), admin_badge_path(badge), method: :delete, data: { confirm: t('sure') } %></td>

</tr>

app/views/admin/badges/_form.html.erb
<div class='container'>
  <%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>
  <div class="form">

    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %><br>

    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: 'form-control' %><br>

    <div><%= form.label :condition %></div>
    <%= form.select :condition, [[t('.first_test'), 'first_test'],
                                 [t('.all_tests_in_category'), 'all_tests_in_category'],
                                 [t('.all_tests_with_level'), 'all_tests_with_level'],
                                 [t('.test_on_the_first_try'), 'test_on_the_first_try']] %><br>

    <%= form.label :condition_parameter %>
    <%= form.text_field :condition_parameter, class: 'form-control' %><br>

    <div class='mt-2'>
      <%= link_to t('back'), admin_badges_path, class: "btn btn-secondary btn-sm" %>
      <%= form.submit %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/badges/edit.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form' %>

app/views/admin/badges/index.html.erb
<%= render 'shared/errors', resource: @badge %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= t('.image') %></th>
      <th><%= t('.name') %></th>
      <th colspan="2"><%= t('.actions') %></th>
    </tr>
 </thead>

  <%= render @badges %>
</table>

<p>
  <%= link_to t('.new_badge'), new_admin_badge_path, class: "btn btn-primary btn-sm" %>
</p>

app/views/admin/badges/new.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form', badge: @badge %>

app/views/admin/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= badge_image_helper(@badge) %>
</p>
<p>
  <%= @badge.name %>
</p>

<%= link_to t('back'), admin_badges_path, class: "btn btn-secondary btn-sm" %>
<%= link_to t('edit'), edit_admin_badge_path, class: "btn btn-secondary btn-sm" %>