config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  resources :badges, only: %i[ index index_user ]
  get :user_badges, to: 'badges#index_user'

  resources :feedbacks, only: %i[ new create ]

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[ show update ] do
    get :result, on: :member
    post 'gist', to: "gists#create", on: :member
  end

  namespace :admin do
    resources :badges
    resources :feedbacks, only: %i[ index ]

    get 'gists', to: "gists#index" 
    
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < User
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers
    errors.add(:max, "can't have more than 4 answers") if question.answers.count > 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  CONDITIONS = %w[ all_tests_in_category all_tests_with_level first_test test_on_the_first_try ].freeze

  has_many :badge_users, dependent: :destroy
  has_many :users, through: :badge_users

  validates :condition, inclusion: { in: CONDITIONS, message: "%{value} is not a valid condition." }
  validates :name, :condition, :image_url, presence: true
end

app/models/badge_user.rb
class BadgeUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope {order(title: :ASC)}

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy_level, -> { by_level(0..1) }
  scope :medium_level, -> { by_level(2..4) }
  scope :high_level, -> { by_level(5..Float::INFINITY) }
  scope :by_level, ->(level) { where(level: level) }
  scope :by_category, -> (category_id) { joins(:category)
                                      .where(categories: { id: category_id }) }
  scope :published, -> { where(published: true) }

  def self.tests_by_category(category)
    by_category(category).pluck(:title).order(title: :DESC)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  CORRECT_QUESTIONS_RATIO = 85.freeze

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :before_validation_set_current_question, on: :create

  scope :user_successful, ->(user) { where(user_id: user, successful: true) }
  scope :tests_of_user, ->(user, testt) { where(user_id: user, test_id: testt) }

  def position_of_current_question
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def successful?
    correct_question_percentage >= CORRECT_QUESTIONS_RATIO
  end

  def correct_question_percentage
    (correct_questions.to_f / all_questions * 100).round(2)
  end

  def all_questions
    test.questions.count
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    self.successful = true if self.successful?
    self.current_question = next_question
    save!
  end

  private

  def before_validation_set_current_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :badge_users, dependent: :destroy
  has_many :badges, through: :badge_users

  has_many :feedbacks, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :authored_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :successful_tests, -> { where(test_passages: { successful: true }) }, 
           through: :test_passages, source: :test

  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true, 
            format: { with: URI::MailTo::EMAIL_REGEXP }

  def user_tests(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :DESC).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

  def successful_tests_by_level(level)
    successful_tests.where(level: level)
  end

  def successful_tests_by_category(category_id)
    successful_tests.where(category_id: category_id)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @test_passage = TestPassage.find(params[:id])
    @question = @test_passage.current_question
    result = GistQuestionService.new(@question)
    gist = result.call

    flash_options = if result.success?
      current_user.gists.create!(question: @question, url: gist.html_url)
      { notice: t('.success', gist_url: view_context.link_to('Gist', gist.html_url)) }
    else
      { alert: t('.failure') }
    end
    redirect_to @test_passage, flash_options  
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def github_url(author, repo)
    link_to repo, "https://github.com/#{author}/#{repo}", target: :blank
  end

  def current_year
    Date.current.year
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_image_helper(badge)
    badge.image_url.capitalize == 'None' ? badge.image_url : (image_tag badge.image_url, class: 'img-thumbnail w-25')
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_navigation.html.erb
<% if user_signed_in? %>
  <div class="navbar sticky-top navbar-light bg-light px-5">
    <p>
      <%= t('.admin_panel', name: current_user.first_name) %>
      <%= link_to 'Guru', admin_tests_path, class: 'navbar-brand' %>
    </p>

    <p>
      <%= link_to 'All Gists', admin_gists_path, class: 'nav-link' %>
    </p>

    <p>
      <%= link_to 'All Feedbacks', admin_feedbacks_path, class: 'nav-link' %>
    </p>

    <p>
      <%= link_to 'All Badges', admin_badges_path, class: 'nav-link' %>
    </p>

    <p>
      <%= link_to t('.exit'), destroy_user_session_path, method: :delete %>
    </p>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "admin/navigation" %>

    <div class="container">
      <%= render 'shared/flash' %>
      <div class="row justify-content-center mt-5">

        <div class="col col-md-8">
          <%= yield %>
        </div>
        
      </div>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <div class="row justify-content-center mt-5">

        <div class="col col-md-8">
          <%= yield %>
        </div>
        
      </div>
    </div>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: {resource_id: resource.id} do %>

    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message.html_safe, 
                  class: "alert alert-#{key} mt-3" %>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light px-3">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= current_year %> | Maksim Korelskii | <%= github_url('MaksimKorelskii', 'TestGutu') %><br>
      Учебный проект по курсу "Основы Ruby on Rails". 
      Веб-приложение для викторин и тестов.
      <%= link_to 'Онлайн-школа Thinknetica', 'http://thinknetica.com/', target: :blank, 'rel': 'no-follow' %>
    </li>
  </ul>
</nav>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <div class="navbar sticky-top navbar-light bg-light px-5">
    <p>
      <%= t('.panel', name: current_user.first_name) %> <%= link_to 'Guru', root_path %>
    </p>

    <p>
      <%= link_to t('.exit'), destroy_user_session_path, method: :delete %>
    </p>
  </div>
<% else %>
  <p class="navbar sticky-top navbar-light bg-light px-3">
    <%= link_to t('.signup'), new_user_registration_path %>
    <%= link_to t('.login'), new_user_session_path %> 
  </p>
<% end %>

<% if current_user&.admin? %>
  <div class="navbar sticky-top navbar-light bg-light px-5">
    <%= link_to 'All Badges', badges_path, class: 'nav-link' %>
    <%= link_to 'User Badges', user_badges_path, class: 'nav-link' %>
    <%= link_to t('.transfer'), admin_tests_path, class: 'nav-link' %>
  </div>
<% end %>