config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  resources :badges, only: %i[ index index_user ]
  get :user_badges, to: 'badges#index_user'

  resources :feedbacks, only: %i[ new create ]

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[ show update ] do
    get :result, on: :member
    post 'gist', to: "gists#create", on: :member
  end

  namespace :admin do
    resources :badges
    resources :feedbacks, only: %i[ index ]

    get 'gists', to: "gists#index" 
    
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  CORRECT_QUESTIONS_RATIO = 85.freeze

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :before_validation_set_current_question, on: :create

  scope :user_successful, ->(user) { where(user_id: user, successful: true) }
  scope :tests_of_user, ->(user, testt) { where(user_id: user, test_id: testt) }

  def position_of_current_question
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def successful?
    correct_question_percentage >= CORRECT_QUESTIONS_RATIO
  end

  def correct_question_percentage
    (correct_questions.to_f / all_questions * 100).round(2)
  end

  def all_questions
    test.questions.count
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    self.successful = true if self.successful?
    self.current_question = next_question
    save!
  end

  private

  def before_validation_set_current_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[ result show update ]

  def show
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      BadgeService.new(@test_passage).call if @test_passage.successful
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end
  
  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def test_passage_result(test_passage)
    if test_passage.successful
      "<h2 class='success'>
        Result #{test_passage.correct_question_percentage}% You passed!
      </h2>".html_safe
    else
      "<h2 class='failure'>
        Result #{test_passage.correct_question_percentage}% You failed.
      </h2>".html_safe
    end
  end
end

app/views/test_passages/result.html.erb
<h1><%= @test_passage.test.title %> was completed!</h1>

<%= test_passage_result(@test_passage) %>

<%= link_to t('.back'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.passing')%> <%= @test_passage.test.title %></h1>

<%= @test_passage.position_of_current_question %> / <%= @test_passage.all_questions %><br>

<%= content_tag :span, 
                class: 'progress-bar align-middle', 
                data: { position_of_current_question: @test_passage.position_of_current_question, 
                        all_questions: @test_passage.all_questions } do %>
<% end %>

<%= t('.timer') %>
  <div class="timer" data-timer="<%= @test_passage.time_left %>">
    <div>
      <%= @test_passage.time_left %>
    </div>
  </div>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids,
                                  @test_passage.current_question.answers,
                                  :id,
                                  :body,
                                  include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p>
    <%= link_to 'Gist question', 
                gist_test_passage_path(@test_passage), 
                method: :post %>
  </p>

  <p>
    <%= form.button 'Next', id: 'next_button', type: "submit" %>
  </p>
<% end %>