config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  resources :badges, only: %i[ index index_user ]
  get :user_badges, to: 'badges#index_user'

  resources :feedbacks, only: %i[ new create ]

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[ show update ] do
    get :result, on: :member
    post 'gist', to: "gists#create", on: :member
  end

  namespace :admin do
    resources :badges
    resources :feedbacks, only: %i[ index ]

    get 'gists', to: "gists#index" 
    
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers
    errors.add(:max, "can't have more than 4 answers") if question.answers.count > 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :set_question, only: %i[ new create ]
  before_action :set_answer, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to [:admin, @answer], notice: "Answer was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer], notice: "Answer was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question], notice: "Answer was successfully destroyed."
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end
  
  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to 'Show', admin_answer_path(answer), class: "btn btn-secondary btn-sm" %>
  <%= link_to 'Edit', edit_admin_answer_path(answer), class: "btn btn-secondary btn-sm" %>
  <%= link_to 'Destroy', 
              admin_answer_path(answer), 
              method: :delete, 
              data: { confirm: 'Are you sure?' }, 
              class: "btn btn-secondary btn-sm" %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [ :admin, @question, @answer ], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Edit Answer</h1>

<p><%= @answer.question.body %></p>

<%= render 'form' %>
<%= link_to 'Back', admin_question_path(@answer.question), 
    class: "btn btn-secondary btn-sm" %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p><%= @question.body %></p>

<%= render 'form' %>
<%= link_to 'Back', admin_question_path(@question), class: "btn btn-secondary btn-sm" %>

app/views/admin/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body%>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', admin_question_path(@answer.question), 
    class: "btn btn-secondary btn-sm" %>